# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-16 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('uin', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
            ],
        ),
    ]
